import { item } from '../Item';
import { AMMO_SCAVENGER } from './AMMO_SCAVENGER';
import { BOUNDLESS_SPIRIT } from './BOUNDLESS_SPIRIT';
import { BULLET_RESIST_SHREDDER } from './BULLET_RESIST_SHREDDER';
import { COLD_FRONT } from './COLD_FRONT';
import { CURSE } from './CURSE';
import { DECAY } from './DECAY';
import { DIVINERS_KEVLAR } from './DIVINERS_KEVLAR';
import { DURATION_EXTENDER } from './DURATION_EXTENDER';
import { ECHO_SHARD } from './ECHO_SHARD';
import { ESCALATING_EXPOSURE } from './ESCALATING_EXPOSURE';
import { ETHEREAL_SHIFT } from './ETHEREAL_SHIFT';
import { EXTRA_CHARGE } from './EXTRA_CHARGE';
import { EXTRA_SPIRIT } from './EXTRA_SPIRIT';
import { IMPROVED_BURST } from './IMPROVED_BURST';
import { IMPROVED_COOLDOWN } from './IMPROVED_COOLDOWN';
import { IMPROVED_REACH } from './IMPROVED_REACH';
import { IMPROVED_SPIRIT } from './IMPROVED_SPIRIT';
import { INFUSER } from './INFUSER';
import { KNOCKDOWN } from './KNOCKDOWN';
import { MAGIC_CARPET } from './MAGIC_CARPET';
import { MYSTIC_BURST } from './MYSTIC_BURST';
import { MYSTIC_REACH } from './MYSTIC_REACH';
import { MYSTIC_REVERB } from './MYSTIC_REVERB';
import { MYSTIC_SLOW } from './MYSTIC_SLOW';
import { MYSTIC_VULNERABILITY } from './MYSTIC_VULNERABILITY';
import { QUICKSILVER_RELOAD } from './QUICKSILVER_RELOAD';
import { RAPID_RECHARGE } from './RAPID_RECHARGE';
import { REFRESHER } from './REFRESHER';
import { SILENCE_GLYPH } from './SILENCE_GLYPH';
import { SLOWING_HEX } from './SLOWING_HEX';
import { SPIRIT_STRIKE } from './SPIRIT_STRIKE';
import { SUPERIOR_COOLDOWN } from './SUPERIOR_COOLDOWN';
import { SUPERIOR_DURATION } from './SUPERIOR_DURATION';
import { SUPPRESSOR } from './SUPPRESSOR';
import { SURGE_OF_POWER } from './SURGE_OF_POWER';
import { TORMENT_PULSE } from './TORMENT_PULSE';
import { WITHERING_WHIP } from './WITHERING_WHIP';

export const ALL_SPIRIT_ITEMS = [
  AMMO_SCAVENGER,
  BOUNDLESS_SPIRIT,
  BULLET_RESIST_SHREDDER,
  COLD_FRONT,
  CURSE,
  DECAY,
  DIVINERS_KEVLAR,
  DURATION_EXTENDER,
  ECHO_SHARD,
  ESCALATING_EXPOSURE,
  ETHEREAL_SHIFT,
  EXTRA_CHARGE,
  EXTRA_SPIRIT,
  IMPROVED_BURST,
  IMPROVED_COOLDOWN,
  IMPROVED_REACH,
  IMPROVED_SPIRIT,
  INFUSER,
  KNOCKDOWN,
  MAGIC_CARPET,
  MYSTIC_BURST,
  MYSTIC_REACH,
  MYSTIC_REVERB,
  MYSTIC_SLOW,
  MYSTIC_VULNERABILITY,
  QUICKSILVER_RELOAD,
  RAPID_RECHARGE,
  REFRESHER,
  SILENCE_GLYPH,
  SLOWING_HEX,
  SPIRIT_STRIKE,
  SUPERIOR_COOLDOWN,
  SUPERIOR_DURATION,
  SUPPRESSOR,
  SURGE_OF_POWER,
  TORMENT_PULSE,
  WITHERING_WHIP,
].map((description) => item(description));
