import { item } from '../Item';
import { AMMO_SCAVENGER as AMMO_SCAVENGER_DESCRIPTION} from './AMMO_SCAVENGER';
import { BOUNDLESS_SPIRIT as BOUNDLESS_SPIRIT_DESCRIPTION } from './BOUNDLESS_SPIRIT';

export const AMMO_SCAVENGER = item(AMMO_SCAVENGER_DESCRIPTION);
export const BOUNDLESS_SPIRIT = item(BOUNDLESS_SPIRIT_DESCRIPTION);
